---
- name: "Initialize role | {{ _title_pfx }}"
  tags: always
  block:
    - name: "Display title | Init | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg:
          - "######################################################################################"
          - "##                        PROXMOX VIRTUAL ENVIRONMENT VMs                           ##"
          - "######################################################################################"

    - name: "Header | Init | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "---------------------------------- INIT ----------------------------------"

    - name: "Ensure tmp directory exists | Init | {{ _title_pfx }}"
      ansible.builtin.tempfile:
        state: directory
        suffix: "pve_vm"
      register: _tmp_dir

    - name: "Check required parameters | Init | {{ _title_pfx }}"
      ansible.builtin.assert:
        that:
          - "{{ item }} | d('',true) | length > 0"
        fail_msg: "Required parameter '{{ item }}' is not defined."
        success_msg: "Required parameter '{{ item }}' is ok."
        quiet: true
      loop:
        - pve_vm__api_host
        - pve_vm__api_user
        - pve_vm__api_password
        - pve_vm__node
        - pve_vm__vm_os_type
        - pve_vm__vm_os_name
        - pve_vm__provision_type
