---
- name: "Role Managing Proxmox Virtual Environment VMs | {{ _title_pfx }}"
  block:
    - name: "Initialize role | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: init.yml
      tags: [always]

    - name: "Download template for cloud images VM | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: download.yml
      tags: [never, download]

    - name: "Provision VM | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: provision.yml
      tags: [never, provision]

    - name: "Unprotect VM | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: unprotect.yml
      tags: [never, unprotect]

    - name: "Erase VM or Templete | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: erase.yml
      tags: [never, erase]

    - name: "Finalize role | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: finish.yml
      tags: [always]
