---
name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4.2.2

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.5.0
        with:
          requirements_file: requirements.yml
